plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.2.20'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

ext {
    springVersion = '7.0.0'

    deps = [
       springCore : "org.springframework:spring-core:$springVersion",
       springContext : "org.springframework:spring-context:$springVersion",
    ]
}

dependencies {
    implementation deps.springCore
    implementation deps.springContext

    testImplementation 'org.jetbrains.kotlin:kotlin-test'
}

test {
    useJUnitPlatform()
}

kotlin {
    jvmToolchain(22)
}