db:
  username: postgres
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost,127.0.0.1
  pool:
    size: 12
    timeout: 100
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2

#spring.profiles.active: qa
app:
  common:
    logging:
      enabled: true
      log-level: trace
  simple:
    enabled: true

logging:
  level:
    root: info
    org.springframework.jdbc.core: trace
  file:
    name: build/logs/farshonok.log
    path: /

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  liquibase:
    change-log: classpath:/db/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
    open-in-view: false
  messages:
    basename: strings
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URL}
            scope:
              - openid
              - email
              - profile
springdoc:
  swagger-ui:
    oauth:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      scopes:
        - openid
        - email
        - profile
    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html